OnlinePortfolio/urls.py
from django.contrib import admin
from django.urls import path,include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),

    # path('cms/', include('cms.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from cms.views import savedata
from . import views
app_name='base'

urlpatterns = [
    path ('', views.home, name='home'),
    path ('About', views.abouts, name='about'),
    path ('Resume', views.resume, name='resume'),
    path ('Contact', views.contact, name='contact'),
    path ('Gallery', views.gallery, name='gallery'),
    path ('Project', views.project, name='project'),
    path ('Admin', views.admin, name='admin'),
    path ('Admin/savedata', savedata, name='savedata'),
    path ('login', views.login, name='login'),
    path ('logout', views.logout, name='logout'),

]

base/models.py
from django.db import models

# Create your models here.

cms/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
 
class User (AbstractUser):
    intro1 = models.TextField(null = True, blank = True)
    intro2 = models.TextField(null = True, blank = True)
    picture = models.ImageField(upload_to='images/', null= True, blank=True)

    name = models.TextField( null = True, blank = True)
    facebook = models.TextField( null = True, blank = True)
    github = models.TextField( null = True, blank = True)
    discord = models.TextField( null = True, blank = True)
    linkedin = models.TextField( null = True, blank = True)
    twitter = models.TextField( null = True, blank = True)

    phrase = models.TextField( null = True, blank = True)
    description = models.TextField( null = True, blank = True)
    degree = models.TextField( null = True, blank = True)
    birthday = models.TextField( null = True, blank = True)
    phone = models.TextField(max_length=11, null = True, blank = True)
    city = models.TextField( null = True, blank = True)
    age = models.TextField( null = True, blank = True)
    email = models.TextField( null = True, blank = True)
    githubname = models.TextField( null = True, blank = True)

    htmlcheckbox = models.BooleanField(default=False)
    cssCheckbox = models.BooleanField(default=False)
    javascriptCheckbox = models.BooleanField(default=False)
    reactCheckbox = models.BooleanField(default=False)
    tailwindCheckbox = models.BooleanField(default=False)
    pythonCheckbox = models.BooleanField(default=False)
    javaCheckbox = models.BooleanField(default=False)
    MongoDBCheckbox = models.BooleanField(default=False)
    nodejsCheckbox = models.BooleanField(default=False)
    flutterCheckbox = models.BooleanField(default=False)
    kotlinCheckbox = models.BooleanField(default=False)

    troubleshootingCheckbox = models.BooleanField(default=False)
    webdevCheckbox = models.BooleanField(default=False)
    networkCheckbox = models.BooleanField(default=False)
    emailCheckbox = models.BooleanField(default=False)

    
    school = models.TextField( null = True, blank = True)
    gradyear = models.TextField( null = True, blank = True)
    degreeDesc = models.TextField( null = True, blank = True)
   
    degree2 = models.TextField( null = True, blank = True)
    school2 = models.TextField( null = True, blank = True)
    gradyear2 = models.TextField( null = True, blank = True)
    degreeDesc2 = models.TextField( null = True, blank = True)

    jobtitle = models.TextField( null = True, blank = True)
    jobyear = models.TextField( null = True, blank = True)
    companyname = models.TextField( null = True, blank = True)
    JobDescri1 = models.TextField( null = True, blank = True)
    JobDescri2 = models.TextField( null = True, blank = True)
    JobDescri3 = models.TextField( null = True, blank = True)
    JobDescri4 = models.TextField( null = True, blank = True)

    roletitle = models.TextField( null = True, blank = True)
    roleyear = models.TextField( null = True, blank = True)
    ojtcompanyname = models.TextField( null = True, blank = True)
    roleDescri1 = models.TextField( null = True, blank = True)
    roleDescri2 = models.TextField( null = True, blank = True)
    roleDescri3 = models.TextField( null = True, blank = True)
    roleDescri4 = models.TextField( null = True, blank = True)


    def str(self):
        return self.email or str(self.id)

cms/forms.py
from django.forms import ModelForm 
from .models import *
class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['intro1','intro2','name','facebook','github','linkedin','twitter','discord','phrase','description','degree','birthday','phone','city','age','email','htmlcheckbox','githubname',
        'cssCheckbox','javascriptCheckbox','reactCheckbox','tailwindCheckbox','pythonCheckbox','javaCheckbox','MongoDBCheckbox','nodejsCheckbox','flutterCheckbox','kotlinCheckbox','troubleshootingCheckbox','webdevCheckbox','networkCheckbox','emailCheckbox','school',
        'gradyear','school2','gradyear2','degreeDesc2','jobtitle','jobyear','companyname','JobDescri1','JobDescri2','JobDescri3','JobDescri4','roletitle','roleyear','ojtcompanyname',
        'roleDescri1','roleDescri2','roleDescri3','roleDescri4','degreeDesc','degree2','picture']
        

base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from cms.models import *
from django.core.mail import send_mail

# Create your views here.

def home(request):
    user = User.objects.get(id=1)
    context = {'user':user}
    return render(request,'home.html',context)

def abouts(request):
    user = User.objects.get(id=1)
    context = {'user':user}
    return render(request,'About.html',context)
    
def resume(request):
    user = User.objects.get(id=1)
    context = {'user':user}
    return render(request,'resume.html',context)

def contact(request):
    if request.method == 'POST':
        user_instance = User.objects.first()
        email = user_instance.email
        email_address = request.POST['email_address']
        subject = request.POST['subject']
        message = request.POST['message']

        send_mail(subject, message, email_address, [email] )
    return render(request,'contact.html')

def gallery(request):
    return render(request,'gallery.html')

def project(request):
    return render(request,'project.html')

def login(request):
    if request.method == 'POST':
        username= request.POST['username']
        password= request.POST['password']
        user=authenticate(username=username, password=password)
        if user is not None:
            auth_login(request,user)
            return redirect('base:admin')
         
    return render(request,'Admin/login.html')


def logout(request):
    auth_logout(request)
    return redirect ('base:login')


def admin(request):
    if request.user.is_authenticated:
        user = User.objects.get(username='admin')
        context = {'user':user}
        return render(request,'Admin/admin.html',context)
    else:
        return redirect ('base:login')



def contactMe(subject, message, email_address, email, fail_silently=False):
    try:
        send_mail(subject, message, email_address, [email], fail_silently=fail_silently)
    except Exception as e:
        print(f"Error sending email: {e}") 

    return render()
        
        

cms/views.py
from django.shortcuts import render
from .forms import *
from .models import *
from django.shortcuts import redirect

# Create your views here.
def savedata(request):
    if request.method == 'POST':
        user = User.objects.get(id=1)
        form = UserForm(request.POST,request.FILES,instance=user)
        if form.is_valid():
            form.save()
            return redirect('base:admin')
        else:
            print(form.errors)
            return redirect('base:admin')


templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title></title>
    <link rel="stylesheet" href='{% static "css/main.css" %}'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href='https://icons.getbootstrap.com/icons' rel='stylesheet'>

    <script src='{% static "css/main.js" %}'></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>
<body>
  <div class="text-container1">
    {% include "homecontent.html"%}
    
  </div>


  <div class="gradient-bg">
    <svg xmlns="http://www.w3.org/2000/svg">
      <defs>
        <filter id="goo">
          <feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />
          <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -8" result="goo" />
          <feBlend in="SourceGraphic" in2="goo" />
        </filter>
      </defs>
    </svg>
    <div class="gradients-container">
      <div class="g1"></div>
      <div class="g2"></div>
      <div class="g3"></div>
      <div class="g4"></div>
      <div class="g5"></div>
      <div class="interactive"></div>
    </div>
    
  </div>
 
    
</body>
</html>

templates/homecontent.html
<header id="header">
    <div class="row">
      <div class="col">
        <div class="container-fluid">
          <h1><a href="index.html">{{user.name}}</a></h1>
          <h2>Your local <span id="role">Project Manager</span> from Zamboanga</h2>

          <script>
            const roles = ['Graphic Designer', 'IT Support', 'Web Developer'];
            const roleSpan = document.getElementById('role');
            let index = 0;
            setInterval(() => {
                roleSpan.textContent = roles[index];
                index = (index + 1) % roles.length;
            }, 6000);
          </script>
    
          <nav id="navbar" class="navbar">
            <ul>
              <li><a class="nav-link active" href="#header">Home</a></li>
              <li><a class="nav-link" href="{% url 'base:about' %}">About</a></li>
              <li><a class="nav-link" href="{% url 'base:resume' %}">Resume</a></li>
              <li><a class="nav-link" href="{% url 'base:contact' %}">Contact</a></li>
              
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
          </nav><!-- .navbar -->
    
          <div class="social-links">
            <a href="{{user.facebook}}" class="instagram"><i class="bi bi-instagram"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
              <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
            </svg></i></a>
            <a href="{{user.github}}" class="linkedin"><i class="bi bi-linkedin"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
              <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
            </svg></i></a>
            <a href="{{user.discord}}" class="linkedin"><i class="bi bi-linkedin"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-discord" viewBox="0 0 16 16">
              <path d="M13.545 2.907a13.2 13.2 0 0 0-3.257-1.011.05.05 0 0 0-.052.025c-.141.25-.297.577-.406.833a12.2 12.2 0 0 0-3.658 0 8 8 0 0 0-.412-.833.05.05 0 0 0-.052-.025c-1.125.194-2.22.534-3.257 1.011a.04.04 0 0 0-.021.018C.356 6.024-.213 9.047.066 12.032q.003.022.021.037a13.3 13.3 0 0 0 3.995 2.02.05.05 0 0 0 .056-.019q.463-.63.818-1.329a.05.05 0 0 0-.01-.059l-.018-.011a9 9 0 0 1-1.248-.595.05.05 0 0 1-.02-.066l.015-.019q.127-.095.248-.195a.05.05 0 0 1 .051-.007c2.619 1.196 5.454 1.196 8.041 0a.05.05 0 0 1 .053.007q.121.1.248.195a.05.05 0 0 1-.004.085 8 8 0 0 1-1.249.594.05.05 0 0 0-.03.03.05.05 0 0 0 .003.041c.24.465.515.909.817 1.329a.05.05 0 0 0 .056.019 13.2 13.2 0 0 0 4.001-2.02.05.05 0 0 0 .021-.037c.334-3.451-.559-6.449-2.366-9.106a.03.03 0 0 0-.02-.019m-8.198 7.307c-.789 0-1.438-.724-1.438-1.612s.637-1.613 1.438-1.613c.807 0 1.45.73 1.438 1.613 0 .888-.637 1.612-1.438 1.612m5.316 0c-.788 0-1.438-.724-1.438-1.612s.637-1.613 1.438-1.613c.807 0 1.451.73 1.438 1.613 0 .888-.631 1.612-1.438 1.612"/>
            </svg></i></a>
            <a href="{{user.twitter}}" class="linkedin"><i class="bi bi-linkedin"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telegram" viewBox="0 0 16 16">
              <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.287 5.906q-1.168.486-4.666 2.01-.567.225-.595.442c-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294q.39.01.868-.32 3.269-2.206 3.374-2.23c.05-.012.12-.026.166.016s.042.12.037.141c-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8 8 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629q.14.092.27.187c.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.4 1.4 0 0 0-.013-.315.34.34 0 0 0-.114-.217.53.53 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09"/>
            </svg></i></a>
            <a href="{{user.linkedin}}" class="linkedin"><i class="bi bi-linkedin"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
              <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
            </svg></i></a>
          </div>
    
        </div>
      </div>
      <div class=" container-fluid col">
        <div class="description">
          <p>{{user.intro1}}</p>
          <p>{{user.intro2}}</p> 
        </div>

        <!-- <div class="row">
          <div class="col-sm-6">
            <div class="card-details">
              <div class="card-body">
                <h5 class="card-title">Art Gallery</h5>
                <p class="card-text">Mix things of School projects and Spare time as a hobby</p>
                <button class="general_btn" type="button" style="color: white;"><a href="{% url 'base:gallery' %}">Click Me</a></button>
              </div>
            </div>
          </div>
        </div> -->
      </div>
    </div>
</header>

templates/nav.html
<nav class="navbar navbar-expand-sm navbar-transparent bg-transparent">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'base:home' %}">Lester Portfolio</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar" aria-controls="mynavbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="mynavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:resume' %}">Resume</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:contact' %}">Contact</a>
        </li>
      </ul>
    </div>
    <div class="ml-auto">
      <button type="button" onclick="window.location.href='https://drive.google.com/file/d/1kZSG1CfUgumwg4iCpEAWsHntoBz_EkgX/view?usp=drive_link'">Download CV</button>
    </div>
  
  </div>
</nav>

<style>
  /* Default button styles */
  button {
    background-color: transparent;
    color: white;
    padding: 10px 20px;
    text-align: center;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    box-shadow: 0 5px 20px rgba(0, 0, 0, 0.5);
    border: none;
  }

  /* Change color on hover */
  button:hover {
    background-color: #45a049;
  }

  
</style>

templates/resume.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title></title>
    <link rel="stylesheet" href='{% static "css/main.css" %}'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href='https://icons.getbootstrap.com/icons' rel='stylesheet'>
  </head>
<body>
  <div class="text-container1">
    {% include "nav.html"%}

    <section id="resume" class="resume">
      <div class="container">
  
        <div class="section-title">
          <h2>Resume</h2>
          <p>Academic Attainment and Employment Record</p>
        </div>
  
        <div class="row">
          <div class="col-lg-6">
            <h3 class="resume-title">Sumary</h3>
            <div class="resume-item">
              <h4>{{user.name}}</h4>
              <p><em>{{user.phrase}}</em></p>
              <p>
              <ul>
                <li>{{user.city}}</li>
                <li>{{user.phone}}</li>
                <li>{{user.email}}</li>
              </ul>
              </p>
            </div>
  
            <h3 class="resume-title">Education</h3>
            <div class="resume-item">
              <h4>{{user.degree}}</h4>
              <h5>{{user.gradyear}}</h5>
              <p><em>{{user.school}}</em></p>
              <p>{{user.degreeDesc}}</p>
            </div>
            <div class="resume-item">
              <h4>{{user.degree2}}</h4>
              <h5>{{user.gradyear2}}</h5>
              <p><em>{{user.school2}}</em></p>
              <p>{{user.degreeDesc2}}</p>
            </div>
          </div>

          <div class="col-lg-6">
            <h3 class="resume-title">Professional Experience</h3>
            <div class="resume-item">
              <h4>{{user.jobtitle}}</h4>
              <h5>{{user.jobyear}}</h5>
              <p><em>{{user.companyname}}</em></p>
              <p>
              <ul>
                <li>{{user.JobDescri1}}</li>
                <li>{{user.JobDescri2}}</li>
                <li>{{user.JobDescri3}}</li>
                <li>{{user.JobDescri4}}</li>
              </ul>
              </p>
            </div>
            <h3 class="resume-title">School Experience</h3>
            <div class="resume-item">
              <h4>{{user.roletitle}}</h4>
              <h5>{{user.roleyear}}</h5>
              <p><em>{{user.ojtcompanyname}} </em></p>
              <p>
              <ul>
                <li>{{user.roleDescri1}}</li>
                <li>{{user.roleDescri2}}</li>
                <li>{{user.roleDescri3}}</li>
                <li>{{user.roleDescri4}}</li>
              </ul>
              </p>
            </div>
            <br>
            <!-- <div class="row">
              <div class="col-sm-6">
                <div class="card-details">
                  <div class="card-body">
                    <h5 class="card-title">Art Gallery</h5>
                    <p class="card-text">Mix things of School projects and Spare time as a hobby</p>
                    <button class="general_btn" type="button" style="color: white;"><a href="{% url 'base:gallery' %}">Click Me</a></button>
                  </div>
                </div>
              </div>
            </div> -->
            <br>
          </div>
          
        </div>
      </div>
    </section><!-- End Resume Section -->
    
  
    
  </div>


  <div class="gradient-bg">
    <svg xmlns="http://www.w3.org/2000/svg">
      <defs>
        <filter id="goo">
          <feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />
          <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -8" result="goo" />
          <feBlend in="SourceGraphic" in2="goo" />
        </filter>
      </defs>
    </svg>
    <div class="gradients-container">
      <div class="g1"></div>
      <div class="g2"></div>
      <div class="g3"></div>
      <div class="g4"></div>
      <div class="g5"></div>
      <div class="interactive"></div>
    </div>
    
  </div>
    <script src='{% static "css/main.js" %}'></script>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>       
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>
    
</body>
</html>